

export const OrfuComp = () => {
    return (
      <div>
        <h1>Project Overview</h1>
        <p>
          The founder of this nonprofit, when she founded it, knew only that she
          wanted to combine food and conversation in a way that would inspire
          empathy and cross political divides. My role was originally more
          generically art and graphic-design focused, as that was my skillset at
          the time, and as we were going to be a magazine. However, as we
          developed the ideas and methodologies behind the idea, as well as the
          feasible scale of creating and distributing materials as a team of
          three people, the idea shifted to being a website to 1) be able to
          more efficiently distribute individual parts of what would have been
          the magazine, such as featured articles, tips, and fact sheets, and 2)
          to allow both a) user-generated content (through submitted recipes and
          stories about, for instance, connecting over food, or sharing an
          interesting food-related tale), and b) allow users to easily connect
          with other people who saw Our Recipe for Unity&apos;s vision.
        </p>
        <h1>Project Scope</h1>
        <p>
          Our mission was “To address division in America by promoting and
          fostering compassion, empathy and civil discourse using food as a
          catalyst to bring people together and to create unity.” To that end,
          we needed a website to act as both a place to distribute what was
          intended to be a full library of content, as well as a repository to
          hold content generated by users at scale. Further, we needed that
          website to create a gentle, welcoming atmosphere that would inspire
          calm and curiosity in our users. Furthermore, we needed it to be
          buildable and manageable by three people on a very small budget.
        </p>
        <h1>Technologies Used</h1>
        <ul>
          <li>Adobe Creative Suite and Balsamiq for prototyping</li>
          <li>
            WordPress, with a bevy of plugins including site origin
            page-builder, ninjaforms, WP-Donate, among many others.
          </li>
          <li>SiteGround backendGoDaddy domain hosting</li>
        </ul>
        <h1>Design Process</h1>
        <p>
          The first thing we did, as a few people with little website
          experience, was to find and crawl through other websites that featured
          either designs we liked or which disseminated similar information to
          what we intended to share We set up a projector, took screenshots,
          printed them, and notated every page of every website we visited. The
          actual design process of the site was very amorphous and fluid at
          first, as the website grew with the mission and methods of the
          business; so, after a brief wire framing phase, we delved right into
          building the site itself in WordPress, the framework with which the
          team had the most collective experience at the time, while working
          concurrently on branding the business.
        </p>
        <h1>Development Process</h1>
        <p>
          The development process started with my learning anything about HTML
          and CSS, which I did through freecodecamp. It was then out of the
          frying pan and into the fire, as the team struggled with keeping
          within a small budget, realizing its ambitious goals, and maintaining
          reasonable timelines to be able to pursue an initial release and
          fundraising before money ran out. We had the website staged on
          WordPress, and as we would have meetings and make decisions, I would
          just kind of bounce between the roles of administrator, graphic
          designer, copywriter and editor, web designer. A month&apos;s work
          might have included building the back- and front-end for fact sheets,
          researching, writing, designing, and testing said fact sheets, then
          pivoting to a complete design overhaul before returning to create the
          page for (and create) menus to accompany those fact sheets. There was
          a very fuzzy goal, and we kept working on parts of the site until we
          felt it was ready to test.
        </p>
        <h1>Key Challenges</h1>
        <ul>
          <li>
            Manpower: with such a small team, many shortcuts had to be taken,
            and the use of external tools and plugins was very necessary.
          </li>
          <li>
            Money: we had a very limited budget and couldn&apos;t pay for too
            many premium/pro plugins, so we had to build a couple custom
            components (like a search page) with Googled and cobbled-together
            PHP/HTML/CSS
          </li>
          <li>
            Time: many features, such as account creation, had to be abandoned
            for the sake of having a prototype ready to test.
          </li>
        </ul>
        <h1>Testing</h1>
        <p>
          Other than Googling “best practice for ___”, we relied largely on
          intuition for quality assurance. With little experience and even less
          time, we conducted a very basic test of the website, where we invited
          around 50 people to test a private version of the site and to provide
          feedback that we would incorporate prior to launch.
        </p>
        <h1>Notable Features</h1>
        <p>
          I particularly liked creating the dynamic sidebar, which, when you
          navigated to a new page on the website, would provide both a new quote
          and a Tweet from the ORfU account, as well as the custom search
          feature, which allowed users to search recipes by course, cuisine,
          region of the USA, relevant holidays, tags, states, and keywords.
        </p>
        <h1>Project Outcome</h1>
        <p>
          The website was launched in August of 2019, shortly before the
          expiration of my contract, and the business drew some attention from
          other nonprofits and local media outlets before going on hiatus in
          2021.
        </p>
        <h1>Personal Reflection</h1>
        <p>
          This project really started my journey as a web designer and
          developer, as I don&apos;t know if I&apos;d have even known about it
          as an option for me without having been “forced” to do it by my job.
          I&apos;m now a React developer, and I&apos;m liking it much better
          than the Wordpress/Page builder/plugin approach, so I wish I&apos;d
          known about this option then. I would have had more fun with the
          project, and I would have definitely been able to fill more of our
          goals and complete more of our desired features if I had full
          Javascript control. However, I&apos;m proud of it.
        </p>
        <h1>Future Plans</h1>
        <p>
          The website does not belong to me, and it is currently on hiatus, as
          the executive director returned to school.
        </p>
        <h1>Impact</h1>
        <p>
          While the site was up for only around two years, it garnered
          respectable attention, and the executive director plans to boot the
          site back up as-is (with modern modifications) in the near future.
        </p>
      </div>
    );
  }