//import react elements
import { useRef, useEffect, useState } from "react";
//import images, starting with brand dev
import finalLogo from "/src/assets/logos/orfu.png";
//import graphics
import conceptDiagram from "/src/assets/projects/orfu/graphics/conceptDiagram.png";
import infographicSmall from "/src/assets/projects/orfu/graphics/infographicSmall.png";
import infographic2 from "/src/assets/projects/orfu/graphics/infographic2.png";
//import wireframes
import factSheetFrame from "/src/assets/projects/orfu/wireframes/factSheetFrame.png";
import infoPageFrame from "/src/assets/projects/orfu/wireframes/infoPageFrame.png";
import recipeDetailsFrame from "/src/assets/projects/orfu/wireframes/recipeDetailsFrame.png";
import recipeSubFrame from "/src/assets/projects/orfu/wireframes/recipeSubFrame.png";
import storyFrame from "/src/assets/projects/orfu/wireframes/storyFrame.png";
import storyOnlyFrame from "/src/assets/projects/orfu/wireframes/storyOnlyFrame.png";
import surveyConceptFrame from "/src/assets/projects/orfu/wireframes/surveyConceptFrame.png";
import toolkitConceptFrame from "/src/assets/projects/orfu/wireframes/toolkitConceptFrame.png";
//import screenshots
import mobileSS from "/src/assets/projects/orfu/screenshots/mobile.png";
import desktopSS from "/src/assets/projects/orfu/screenshots/desktop.png";
//import components
import PicCarousel from "/src/components/PicCarousel";
import VisitBlock from "/src/components/VisitBlock";
import c1 from "/src/assets/projects/orfu/brandDev/c1.svg";
import c2 from "/src/assets/projects/orfu/brandDev/c2.svg";
import c3 from "/src/assets/projects/orfu/brandDev/c3.svg";
import c4 from "/src/assets/projects/orfu/brandDev/c4.svg";

export const OrfuComp = () => {
  const logos2 = [c1, c2, c3, c4, finalLogo];
  const frames = [
    factSheetFrame,
    infoPageFrame,
    recipeDetailsFrame,
    recipeSubFrame,
    storyFrame,
    storyOnlyFrame,
    surveyConceptFrame,
    toolkitConceptFrame,
  ];
  const infoGraphics = [conceptDiagram, infographicSmall, infographic2];

  const visitText = "Visit archived site";
  const visitLink = "https://ourrecipeforunity.org/";
  const visitLinkText = "Visit archived site (certain features may not work)"; //visitLinkText

  return (
    <section className="projectContent" id="orfu">
      <section className="projectHeader">
        <h2>Developing Compassion, Creating</h2>
        <PicCarousel
          enableFS={false}
          arrows={false}
          transition="blur"
          border={false}
          images={logos2}
          id="orfuLogos"
          intervalLength={3000}
        />
      </section>
      <div id="orfuContent1">
        <VisitBlock
          mobileSS={mobileSS}
          desktopSS={desktopSS}
          visitText={visitText}
          visitLink={visitLink}
          visitLinkText={visitLinkText}
        />
        <section id="projectBody1">
          <p>
            In order to &quot;address division in America by promoting and
            fostering compassion, empathy and civil discourse using food&quot;,
            we needed a website to act as both a place to distribute what was
            intended to be a full library of marketing materials and content, as
            well as a repository to hold content generated by users at scale, to
            be buildable and manageable by three people on a very small budget.
          </p>
          <p>
            The first thing we did, as a few people with little website
            experience, was to find and crawl through other websites that
            featured either designs we liked or which disseminated similar
            information to what we intended to share; after a brief wireframing
            phase, we delved right into building the site itself in WordPress,
            the framework with which the team had the most collective experience
            at the time, while working concurrently on branding the business.
          </p>
        </section>
      </div>
      <div id="orfuContent2">
        <p>We used the following technologies to build the site:</p>
        <ul id="orfuList">
          <li className="listHeader">
            Prototyping & Wireframing
            <ul id="subList">
              <li>Adobe Creative Suite</li>
              <li>Balsamiq</li>
            </ul>
          </li>
          <li className="listHeader">
            Development
            <ul id="subList">
              <li>WordPress</li>
              <li>SiteOrigin</li>
              <li>Ninjaforms</li>
              <li>WordPress-Donate</li>
            </ul>
          </li>
          <li className="listHeader">
            Hosting
            <ul id="subList">
              <li>SiteGround</li>
              <li>GoDaddy</li>
            </ul>
          </li>
        </ul>
      </div>
      <div id="orfuContent3">
        <PicCarousel
          enableFS={true}
          arrows={true}
          transition="slideDown"
          images={frames}
          id="orfuFrames"
          border={true}
          intervalLength={5000}
        />

        <div id="orfuContentInner">
          <p>
            The development process started with my learning HTML and CSS
            through Freecodecamp. It was then out of the frying pan and into the
            fire; as we worked to realize our ambitious goals, we developed and
            staged on WordPress, and as we would have meetings and make
            decisions, I would bounce between the roles of administrator,
            graphic designer, copywriter and editor, and web designer/developer.
          </p>
          <p>
            We conducted a very basic test of the website, where we invited
            around 50 people to test a private version of the site and to
            provide feedback that we would incorporate prior to our August 2019
            launch.
          </p>
          <p>
            I particularly enjoyed creating the dynamic sidebar, which, when you
            navigated to a new page on the website, would provide both a new
            quote and a Tweet from the ORfU account. I am also proud of a (now
            defunct) feature where stories/recipes added would be added to an
            interactive map showing the breadth of our users.
          </p>
          <p>
            While the site was up for only around two years (it is currently on
            hiatus, as the executive director returned to school), it garnered
            respectable attention, and the executive director plans to boot the
            site back up in the future.
          </p>
        </div>
      </div>
    </section>
  );
};
